# 1. Numpy 배열로 5명 학생의 4과목 성적표를 만들고 축(axis) 기준 통계를 산출하시오

In [119]:
import numpy as np

scores = [88, 92, 79, 95,
          75, 68, 82, 70,
          92, 99, 95, 88,
          60, 72, 65, 58,
          85, 80, 78, 90]

### 1.1 위 리스트를 5행 4열 ndarray로 변환하고 shape, ndim, size, dtype을 출력하시오.

In [120]:
x = np.array(scores).reshape(5, 4)
print("Shape: ", np.shape(x))
print("Dimensions: ", np.ndim(x))
print("Size: ", np.size(x))
print("Dtype: ", x.dtype)

Shape:  (5, 4)
Dimensions:  2
Size:  20
Dtype:  int64


### 1.2 학생 별 평균과 과목 별 평균을 각각 구하시오.

In [121]:
print("학생별 평균: ", np.mean(x, axis=1))
print("과목별 평균: ", np.mean(x, axis=0))

학생별 평균:  [88.5  73.75 93.5  63.75 83.25]
과목별 평균:  [80.  82.2 79.8 80.2]


### 1.3 전체에서 가장 높은 점수와 그 점수가 몇 번째 학생·몇 번째 과목인지 구하시오.

In [122]:
print("가장 높은 점수: ", np.max(x))

max_score = np.where(x == np.max(x))
print("가장 높은 점수를 받은 학생: ", max_score[0][0])
print("가장 높은 점수를 받은 과목: ", max_score[1][0])

가장 높은 점수:  99
가장 높은 점수를 받은 학생:  2
가장 높은 점수를 받은 과목:  1


### 1.4 전체 평균, 표준편차, 분산을 구하시오.

In [123]:
print("전체 평균: ", np.mean(x))
print("전체 표준편차: ", np.std(x))
print("전체 분산: ", np.var(x))

전체 평균:  80.55
전체 표준편차:  11.825713509129164
전체 분산:  139.84750000000003


### 1.5 평균이 80점 이상인 학생의 인덱스와 인원수를 구하고, 해당 학생들의 성적만 잘라내어 출력하시오.

In [124]:
index = np.where(np.mean(x, axis=1) >= 80)
print("80점 이상인 학생들의 인덱스: ", index[0])
print("80점 이상인 학생의 수: ", len(index[0]))

print("해당 학생들: ")
print(x[index])

80점 이상인 학생들의 인덱스:  [0 2 4]
80점 이상인 학생의 수:  3
해당 학생들: 
[[88 92 79 95]
 [92 99 95 88]
 [85 80 78 90]]


### 1.6 90점 이상인 점수의 개수, 100점 이상인 점수가 하나라도 있는지, 모든 점수가 60점 이상인지를 판별하시오.

In [125]:
print("90점 이상인 점수의 개수: ", np.sum(x >= 90))
print("100점 이상인 점수의 유무: ", np.any(x >= 100))
print("모든 점수가 60점 이상인지: ", np.all(x >= 60))

90점 이상인 점수의 개수:  6
100점 이상인 점수의 유무:  False
모든 점수가 60점 이상인지:  False


### 1.7 90점 이상은 'A', 80점 이상은 'B', 나머지는 'C'로 변환한 등급 배열을 만드시오.

In [126]:
new = np.where(x < 80, "C", x)
new = np.where((x > 80) & (x <= 90), "B", new)
new = np.where(x > 90, "A", new)
print(x)
print(new)

[[88 92 79 95]
 [75 68 82 70]
 [92 99 95 88]
 [60 72 65 58]
 [85 80 78 90]]
[['B' 'A' 'C' 'A']
 ['C' 'C' 'B' 'C']
 ['A' 'A' 'A' 'B']
 ['C' 'C' 'C' 'C']
 ['B' '80' 'C' 'B']]


# 2. 8×8 난수 배열을 흑백 이미지로 가정하고 슬라이싱·이진화·좌우 반전을 구현하시오.

### 1. 생성한 img를 출력하시오.

In [127]:
np.random.seed(2024)
img = np.random.randint(0, 256, size=(8, 8))
print(img)

[[136 250  96 128  27  36 190 183]
 [ 41 127 193  60 227  74  66 224]
 [165 252 241 158 111 247 202 110]
 [ 95 111  11  28  91  39  54 114]
 [183  73 102 218 244  42  31  97]
 [150  27  86 119  69 157  61 243]
 [ 54 132  57  86  54 254 148 126]
 [136  18  97  90 202 135 176 232]]


### 2. 이미지 정중앙의 4×4 영역만 잘라내어 출력하시오.

In [128]:
print(img[2:6, 2:6])

[[241 158 111 247]
 [ 11  28  91  39]
 [102 218 244  42]
 [ 86 119  69 157]]


### 3. 짝수 번째 행(0, 2, 4, 6행)만 뽑아내시오.

In [129]:
print(img[::2, ::2])

[[136  96  27 190]
 [165 241 111 202]
 [183 102 244  31]
 [ 54  57  54 148]]


### 4. 128 이상인 픽셀은 255(흰색), 미만인 픽셀은 0(검은색)으로 바꾼 이진화 배열을 만드시오.

In [130]:
binary_img = np.where(img >= 128, 255, 0)
print(binary_img)

[[255 255   0 255   0   0 255 255]
 [  0   0 255   0 255   0   0 255]
 [255 255 255 255   0 255 255   0]
 [  0   0   0   0   0   0   0   0]
 [255   0   0 255 255   0   0   0]
 [255   0   0   0   0 255   0 255]
 [  0 255   0   0   0 255 255   0]
 [255   0   0   0 255 255 255 255]]


### 5. 이진화 결과에서 흰색 픽셀과 검은색 픽셀의 개수를 각각 세시오.

In [131]:
print("검은색: ", np.sum(binary_img == 0))
print("하얀색: ", np.sum(binary_img == 255))

검은색:  36
하얀색:  28


### 6. 원본 이미지를 좌·우 절반으로 분할하시오.

In [132]:
split = np.array_split(img, 2, axis=1)
print(img)
print("Left:\n", split[0])
print("Right:\n", split[1])

[[136 250  96 128  27  36 190 183]
 [ 41 127 193  60 227  74  66 224]
 [165 252 241 158 111 247 202 110]
 [ 95 111  11  28  91  39  54 114]
 [183  73 102 218 244  42  31  97]
 [150  27  86 119  69 157  61 243]
 [ 54 132  57  86  54 254 148 126]
 [136  18  97  90 202 135 176 232]]
Left:
 [[136 250  96 128]
 [ 41 127 193  60]
 [165 252 241 158]
 [ 95 111  11  28]
 [183  73 102 218]
 [150  27  86 119]
 [ 54 132  57  86]
 [136  18  97  90]]
Right:
 [[ 27  36 190 183]
 [227  74  66 224]
 [111 247 202 110]
 [ 91  39  54 114]
 [244  42  31  97]
 [ 69 157  61 243]
 [ 54 254 148 126]
 [202 135 176 232]]


### 7. 분할한 두 조각의 순서를 바꿔 다시 이어 붙여 좌우가 뒤바뀐 이미지를 만드시오.

In [133]:
reversed_img = np.concatenate([split[1], split[0]], axis=1)
print(reversed_img)

[[ 27  36 190 183 136 250  96 128]
 [227  74  66 224  41 127 193  60]
 [111 247 202 110 165 252 241 158]
 [ 91  39  54 114  95 111  11  28]
 [244  42  31  97 183  73 102 218]
 [ 69 157  61 243 150  27  86 119]
 [ 54 254 148 126  54 132  57  86]
 [202 135 176 232 136  18  97  90]]


### 8. 원본 이미지를 1차원으로 펼친 뒤 앞 10개 값과 shape을 출력하시오.

In [139]:
one_dimensional_img = img.ravel()
print(one_dimensional_img)

print("First 10 values: ", one_dimensional_img[:10])
print("Shape: ", np.shape(one_dimensional_img))

[136 250  96 128  27  36 190 183  41 127 193  60 227  74  66 224 165 252
 241 158 111 247 202 110  95 111  11  28  91  39  54 114 183  73 102 218
 244  42  31  97 150  27  86 119  69 157  61 243  54 132  57  86  54 254
 148 126 136  18  97  90 202 135 176 232]
First 10 values:  [136 250  96 128  27  36 190 183  41 127]
Shape:  (64,)


### 9. 128 이상인 픽셀만 골라내어 그 개수와 평균값을 구하시오.

In [135]:
over128 = np.where(img > 128)
print(img[over128])
print("개수: ", len(img[over128]))
print("평균값: ", np.mean(img[over128]))

[136 250 190 183 193 227 224 165 252 241 158 247 202 183 218 244 150 157
 243 132 254 148 136 202 135 176 232]
개수:  27
평균값:  195.4814814814815


# 지점별 판매 데이터에 브로드캐스트와 행렬 연산을 적용해 매출을 분석하시오.

In [136]:
sales = np.array([[120,  80,  45,  60],     # A지점
                  [200, 150,  90,  30],     # B지점
                  [ 75,  60, 120,  95]])    # C지점
price = np.array([1500, 3000, 5000, 2000])  # 제품 1~4 단가

### 1. 브로드캐스트를 이용해 각 지점의 제품별 매출액(수량 × 단가) 행렬을 구하시오. (반복문 금지)

In [140]:
print(sales * price)

[[180000 240000 225000 120000]
 [300000 450000 450000  60000]
 [112500 180000 600000 190000]]


### 2. 행렬곱을 이용해 각 지점의 총매출을 한 번에 구하시오. 또한 제품별 총판매량도 구하시오.

In [146]:
total_sales = np.dot(sales, price)
# total_sales = sales @ price
print("각 지점의 총매출: ", total_sales)
print("제품별 총판매량: ", np.sum(sales, axis=0))

각 지점의 총매출:  [ 765000 1260000 1082500]
제품별 총판매량:  [395 290 255 185]


### 3. 각 제품의 평균 판매량을 구한 뒤, 브로드캐스트로 평균 대비 편차 행렬을 구하시오.

In [147]:
avg_sales = np.mean(sales, axis=0)
print("각 제품의 평균 판매량: ", avg_sales)

diff = sales - avg_sales
print("각 지점의 판매량과 평균 판매량의 차이: \n", diff)


각 제품의 평균 판매량:  [131.66666667  96.66666667  85.          61.66666667]
각 지점의 판매량과 평균 판매량의 차이: 
 [[-11.66666667 -16.66666667 -40.          -1.66666667]
 [ 68.33333333  53.33333333   5.         -31.66666667]
 [-56.66666667 -36.66666667  35.          33.33333333]]


### 4. 각 지점을 기준으로 판매량을 정규화하시오. 결과의 행별 평균이 0, 표준편차가 1이 되는지 확인하시오.

In [155]:
normalized_sales = (sales - np.mean(sales, axis=1, keepdims=True)) / np.std(sales, axis=1, keepdims=True)
print(normalized_sales)

[[ 1.55440457  0.13323468 -1.11028898 -0.57735027]
 [ 1.29337197  0.50951017 -0.43112399 -1.37175815]
 [-0.55555556 -1.22222222  1.44444444  0.33333333]]
