# 260805 Today I Learnt

## Numpy 

(Numerical Python) 

In [9]:
import numpy as np

* np.arange(시작 값, 끝값, step) -> python range()

In [10]:
x = np.arange(10)
print(x)
x = np.arange(10.0)
print(x)
x = np.arange(1, 10, 2)
print(x)
x = np.arange(1, 10, 0.5)
print(x)
x = np.arange(10, 1, -0.5)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1 3 5 7 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


* np.linspace(시작 값, 끝값, 벡터 크기) -> 균일한 간격으로 리스트 크기만큼의 리스트 생성

endpoint = False -> 끝 값 포함여부 옵션

In [11]:
x = np.linspace(1, 20, 5)
print(x)
x = np.linspace(1, 20, 10, endpoint=True)
print(x)

[ 1.    5.75 10.5  15.25 20.  ]
[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


* np.reshape(차원) -> 데이터를 유지하면서 차원의 형태를 변경

-1 일 경우 자동으로 맞춰 생성

In [12]:
x = np.arange(9).reshape(3, 3)
print(x)
x = np.arange(24).reshape(2, 3, 4)
print(x)
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x.reshape(2, 3))
x = np.arange(9).reshape(3, -1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[1 2 3]
 [4 5 6]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


* slicing

In [13]:
x = np.arange(20)
print(x[1:3])
x = np.arange(20).reshape(4, 5)
print(x)
print(x[1:3])
print(x[1:3, 1:3])
x = np.arange(30).reshape(2, 5, 3)
print(x)
print(x[:, 3:5, 1])


[1 2]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 6  7]
 [11 12]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[10 13]
 [25 28]]


* indexing & boolean indexing

In [14]:
x = np.arange(20).reshape(4, 5)
print(x[1][1])
print(x[1, 1])

6
6


* random 

np.random.rand(5, 5) -> 난수가 들어가있는 다양한 형태의 데이터

np.random.randint(1, 10) -> 정수형 난수

np.random.randint(1, 10, size = (5)) -> 정수형 난수 크기 지정

* 특별한 형태의 배열

np.ones -> 모든 값이 1

np.zeroes -> 모든 값이 0

np.eyes(5) -> 단위행렬

ndarray.ravel(order = "C") -> 행렬 펼치기, F -> 열기준

* concatenate -> 배열을 연결

np.concatenate([x, y])

axis = 1 -> 열 기준으로 연결

In [15]:
x = np.arange(1, 4)
y = np.arange(4, 7)
np.concatenate([x, y])

x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)
np.concatenate([x, y])
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

* split -> 배열을 분해

np.split(x, n)

axis = 1 -> 열을 기준으로 분해


In [16]:
x = np.arange(12)
np.split(x, 4)
x = np.arange(16).reshape(4, 4)
np.split(x, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

* broadcast -> 차원이 다른 행렬끼리의 계산

### functions

x = np.arange(4).reshape(2, 2)

y = np.arange(4).reshape(2, 2)

x.dot(y) # 행렬곱

np.transpose(x) # 전치행렬

np.linalg.inv(x) # 역행렬

np.linalg.det(x) # 행렬식

np.mean(x) # 평균

np.median(x) # 중간값

np.std(x) # 표준편차

np.var(x) # 분산

np.sum(x) #

np.sum(데이터, axis=1) #합, 축 변경

np.cumsum(x) # 누적합

np.cumprod(x) # 누적곱

np.min(x) # 최소값

np.argmin(x) #최소값 위치

np.argmax(x) # 최대값 위치

np.any(x > 4) # 하나라도 참이어야 참

np.all(x > 4) # 모든 요소가 참이어야 참

np.where(x > 4) # 조건에 맞는 위치

np.where(x > 4, x,-100) # 조건, True일 경우, False일 경우